---
title: "Assignment 4 - A working Title"
author: "Anthony Luna & Elliott Matthews"
date: "11/9/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```
```{r}
library(tidyverse)
library(janitor)
library(kableExtra)
library(scales)
library(here)
```

### Introduction

### Data and Methods

### Results

#### Results A: Visually Explore changes in annual lobster abundance (counts) by site 

```{r}
lob_raw <- read_csv(here("data","lobster_abundance_sbc_lter.csv"), na = "-99999") %>% 
  clean_names() %>% 
  uncount(weights = count) %>% 
  mutate(cfgn_code = case_when(site %in% c("NAPL","IVEE")~"MPA",TRUE~"non-MPA"))


lob_year_site <- lob_raw %>% 
  group_by(year,site, cfgn_code) %>% 
  summarise(count = n()) 

lob_year_site_plot <- ggplot(data=lob_year_site, aes(x=year,y=count))+
  geom_line(aes(color = site))+
  facet_wrap(~cfgn_code, nrow = 2)+
  labs(title = "Population of Lobsters over time",
    subtitle = "2012-2018",
    caption = "Observed lobster counts from 2012 to 2018 in 5 locations off the coast of Santa Barbara",
    x = "Year",
    y = "Count of Lobsters",
    col = "Site") + 
    theme_minimal() +  
    # This centers our title and subtitle  
    theme(plot.title = element_text(hjust= 0.5),
          plot.subtitle = element_text(hjust= 0.5))
lob_year_site_plot
```

```{r}
#Testing Spaghetti plot for Results A
spaghetti <- lob_year_site %>% 
  mutate( highlight=ifelse(cfgn_code=="MPA", "MPA", "Other")) %>% #ifelse processes a test (if this is true, set = to this, everything else is this)
  ggplot(aes(x=year, y =count, group = site, color = highlight))+
  geom_line() +
 # scale_color_manual(values = c("#31B9CE", "darkgray")) +
  #scale_size_manual(values = c(.2, 2.0))+
  theme_minimal()

spaghetti



##### Or consider this one #####

# Wasn't able to get it to look the way I wanted.  Wanted all of the sites to be on each graph with a single highlighted per facet swap

tmp <- lob_year_site %>% 
  mutate(site2 = site)
tmp %>% 
  ggplot(aes(x = year, y = count)) +
  geom_line(data = tmp %>% dplyr::select(-site), aes(group=site2)) +
  geom_line(aes(color=site)) +
  facet_wrap(~site)
```



#### Results B: Visually explore lobster size distribution shifts by comparing lobster sizes in 2012 and 2018

```{r}
lob_size_2018 <- lob_raw %>% 
  filter(!is.na(size_mm)) %>% 
  filter(year==2018) 

ggplot(lob_size_2018,aes(x=size_mm,fill=year))+
  geom_histogram( color="#e9ecef", alpha=0.6, position = 'identity') +
   # scale_fill_manual(values=c("#69b3a2", "#404080")) +
  facet_wrap(~site)  # I think we should remove scales free. It makes the populations look comprable when they are magnitudes different
```
```{r}
lob_size_2012 <- lob_raw %>%    
  filter(!is.na(size_mm)) %>% 
  filter(year==2012)

ggplot(lob_size_2012,aes(x=size_mm,fill=year))+
  geom_histogram( color="#e9ecef",
                  alpha=0.6, 
                  position = 'identity') +
  facet_wrap(~site)
```


```{r}
# Overlapping Violin plot testing for Results B.  Having difficulty overlapping two independent violin plots due to aes mapping so maybe make a vector with all necessary data from each plot and use that to supply data for one independent plot.

lob_size_2012_test <- lob_size_2012 %>% 
  group_by(site)

lob_size_2018_test <- lob_size_2018 %>% 
  group_by(site)

ggplot() + # To overlay do not insert any data or aes into intial ggplot(). If you do it causes that to be applied to all following plots. In this instance since we are using multiple data frames  we need to map the aes per data frame.
geom_violin(data = lob_size_2012_test, 
            aes (x = site, y = size_mm, fill = site)) +
geom_violin(data = lob_size_2018_test, 
            aes (x = site, y = size_mm, fill = site),
            alpha = 0.50,
            fill = "grey") +
  labs(title = "Comparison of Lobster size in 2012 vs 2018",
       x = "Catch site",
       y = "Size (mm)") +
  theme(plot.title = element_text(hjust= 0.5),
          plot.subtitle = element_text(hjust= 0.5))
  
  #####################  Change legend to show 2018 is grey, and 2012 is solid##############


```


#### Results C: Compare mean lobster sizes at MPA vs. non-MPA status sites in 2012 and 2018

```{r}
### Create data frames for statistical analysis. ###

# Mean size of lobsters in 2012

mpa_size_2012 <- lob_raw %>% 
  filter(year == 2012) %>%
  filter(cfgn_code == "MPA") %>% 
  filter(!is.na(size_mm)) 

non_mpa_size_2012 <- lob_raw %>% 
  filter(year == 2012) %>%
  filter(cfgn_code == "non-MPA") %>% 
  filter(!is.na(size_mm)) 

# Mean size of lobsters in 2018

mpa_size_2018 <- lob_raw %>% 
  filter(year == 2018) %>%
  filter(cfgn_code == "MPA" ) %>% 
  filter(!is.na(size_mm)) 

non_mpa_size_2018 <- lob_raw %>% 
  filter(year == 2018) %>%
  filter(cfgn_code == "non-MPA") %>% 
  filter(!is.na(size_mm))

### Perform t-tests on data to determine if there is a significant difference between lobster sites in:

# 1. 2012 MPA and non MPA sites 

mpa_vs_non_2012 <- t.test(
  mpa_size_2012$size_mm, non_mpa_size_2012$size_mm)

# 2. 2018 MPA and non MPA sites

mpa_vs_non_2018 <- t.test(
  mpa_size_2018$size_mm, non_mpa_size_2018$size_mm)

# 3. MPA sites only 2012 vs 2018

mpa_2012_vs_mpa_2018 <- t.test(
  mpa_size_2012$size_mm, mpa_size_2018$size_mm)

# 4. non MPA sites only 2012 vs 2018

non_mpa_2012_vs_non_mpa_2018 <- t.test(
  non_mpa_size_2012$size_mm, non_mpa_size_2018$size_mm)

mpa_vs_non_2012
mpa_vs_non_2018
mpa_2012_vs_mpa_2018
non_mpa_2012_vs_non_mpa_2018


```

```{r}
### Create summary table with mean, standard deviation, and sample count

final_summary_table <- lob_raw %>% 
  filter(year %in% c(2012, 2018)) %>% 
  group_by(cfgn_code,year) %>% 
  summarize(
    mean = mean(size_mm),
    s_dev = sd(size_mm),
    count = n())

kableExtra::kable(final_summary_table, 
                  caption = "Table 1: Lobster summary statistics",
                  col.names = c("area type",
                                "year",
                                "mean (mm)",
                                "st dev (\u00B1 mm)  ",
                                "count"))
  
```


### Summary

### References